name: mini_design
description: "miniDesign system"
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  slivers: ^0.0.1+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
